{"name": "test_login_failure[payload2]", "status": "passed", "parameters": [{"name": "payload", "value": "{}"}], "start": 1744355972079, "stop": 1744355972584, "uuid": "cc70b09f-afab-4333-9e6c-d9da10b18919", "historyId": "59b52ea95b2027f9348b7d999fb1f45f", "testCaseId": "886369add03fae2429dc3ebb3644b0f9", "fullName": "tests.auth.test_auth#test_login_failure", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "CD4093DYG"}, {"name": "thread", "value": "6820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_auth"}]}