{"name": "test_register[wrong@mail.com-12345-400-error]", "status": "passed", "attachments": [{"name": "stdout", "source": "dedc2b21-1c46-4ebb-8102-c5927eb5d066-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "email", "value": "'wrong@mail.com'"}, {"name": "password", "value": "'12345'"}, {"name": "expected_status", "value": "400"}, {"name": "expected_key", "value": "'error'"}], "start": 1744357293849, "stop": 1744357294478, "uuid": "a088f679-4158-4913-b8dd-475019759b6b", "historyId": "1db0f12adf1fd8baecb44be31744a178", "testCaseId": "43edb6491d02b99dd219a615676e519f", "fullName": "tests.auth.test_register#test_register", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_register"}, {"name": "host", "value": "CD4093DYG"}, {"name": "thread", "value": "16112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_register"}]}