{"name": "test_login[wrong@mail.com-wrong-400-error]", "status": "passed", "parameters": [{"name": "email", "value": "'wrong@mail.com'"}, {"name": "password", "value": "'wrong'"}, {"name": "expected_status", "value": "400"}, {"name": "expected_key", "value": "'error'"}], "start": 1744226128767, "stop": 1744226129417, "uuid": "7b133fa3-8c1f-4d7e-a32e-bda639e4198a", "historyId": "63caa5671c5ad9d3d16759d8e7c499f0", "testCaseId": "65a5e93a0a60b972afeebc280e05de5b", "fullName": "tests.test_auth#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "CD4093DYG"}, {"name": "thread", "value": "1360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}